import type { Metadata } from "next";
import { leagueSpartan } from "./ui/fonts";
import { ProgressProvider } from "@/lib/ProgressContext";

import "./globals.css";


export const metadata: Metadata = {
  title: "ItLegens Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.className} bg-white  antialiased`}
      >
        <ProgressProvider>{children}</ProgressProvider>
      </body>
    </html>
  );
}
